FROM infraframe/base:latest as base

FROM ubuntu:20.04
ARG TARGETARCH

# WORKDIR /home/infraframe/
# # 环境变量
# ENV DEBIAN_FRONTEND=noninteractive
# ENV PREFIX="/home/infraframe/build/libdeps"
# ENV PREFIX_DIR="/home/infraframe/build/libdeps/build"
# ENV PATHNAME="/home/infraframe/scripts"
# ENV PATH=""
# ENV PKG_CONFIG_PATH=${PREFIX_DIR}/lib/pkgconfig
# ENV PATH=${PREFIX}/bin:${PREFIX}/node-v14.21.3-linux-${TARGETARCH}/bin:/usr/bin:$PATH
# # 整个node_modules
# COPY ./apps/ /home/infraframe/dist/apps/
# COPY --from=base /home/infraframe/dist/package.json  /home/infraframe/dist/package.json
# COPY --from=base /home/infraframe/dist/bin /home/infraframe/dist/bin
# COPY --from=base ${PREFIX_DIR} ${PREFIX_DIR}
# COPY --from=base ${PREFIX}/bin ${PREFIX}/bin
# COPY --from=base ${PREFIX}/lib ${PREFIX}/lib
# COPY --from=base ${PREFIX}/node-v14.21.3-linux-${TARGETARCH} ${PREFIX}/node-v14.21.3-linux-${TARGETARCH}
# COPY --from=base ${PREFIX}/nodejs-node-gyp-adcdab2 ${PREFIX}/nodejs-node-gyp-adcdab2
# COPY --from=base /home/infraframe/package.json  /home/infraframe/package.json
# RUN apt-get update && \
#     apt-get install -y \
#         liblog4cxx-dev \
#         net-tools \
#         gstreamer1.0-plugins-ugly \
#         && rm -rf /var/lib/apt/lists/*

WORKDIR /home/infraframe/dist/apps/current_app
CMD node .
