{
    "targets": [
        {
            "target_name": "videoTranscoder-sw",
            "sources": [
                "../addon.cc",
                "../VideoTranscoderWrapper.cc",
                "../VideoTranscoder.cpp",
                "../../../../core/owt_base/I420BufferManager.cpp",
                "../../../../core/owt_base/MediaFramePipeline.cpp",
                "../../../../core/owt_base/FrameConverter.cpp",
                "../../../../core/owt_base/FrameProcessor.cpp",
                "../../../../core/owt_base/FFmpegDrawText.cpp",
                "../../../../core/common/JobTimer.cpp",
                "../../../../core/owt_base/VCMFrameDecoder.cpp",
                "../../../../core/owt_base/VCMFrameEncoder.cpp",
                "../../../../core/owt_base/FFmpegFrameDecoder.cpp",
                "../../../../core/owt_base/FFmpegDrawText.cpp",
                "../../../../core/owt_base/SVTHEVCEncoder.cpp",
                "../../../../core/owt_base/gst/BufferPool.cpp",
                "../../../../core/owt_base/gst/DecoderPipeline.cpp",
                "../../../../core/owt_base/gst/EncoderPipeline.cpp",
                "../../../../core/owt_base/gst/H264VideoDecoders.cpp",
                "../../../../core/owt_base/gst/H264VideoEncoders.cpp",
                "../../../../core/owt_base/gst/Helpers.cpp",
                "../../../../core/owt_base/gst/Support.cpp",
                "../../../../core/owt_base/gst/VideoDecoder.cpp",
                "../../../../core/owt_base/gst/VideoEncoder.cpp",
            ],
            "cflags_cc": [
                "-Wall",
                "-O$(OPTIMIZATION_LEVEL)",
                "-g",
                "-std=c++17",
                "-DWEBRTC_POSIX",
                "<!@(pkg-config --cflags-only-I gstreamer-1.0)",
                "<!@(pkg-config --cflags-only-I glib-2.0)",
                "<!@(pkg-config --cflags glib-2.0)",
                "<!@(pkg-config --cflags fmt)",
            ],
            "cflags_cc!": [
                "-fno-exceptions",
            ],
            "include_dirs": [
                "<!(node -e \"require('nan')\")",
                "..",
                "$(CORE_HOME)/common",
                "$(CORE_HOME)/owt_base",
                "$(CORE_HOME)/../../third_party/webrtc/src",
                "$(CORE_HOME)/../../third_party/webrtc/src/third_party/libyuv/include",
                "$(DEFAULT_DEPENDENCY_PATH)/include",
                "$(CUSTOM_INCLUDE_PATH)",
            ],
            "libraries": [
                "-lboost_thread",
                "-llog4cxx",
                "-L$(CORE_HOME)/../../third_party/webrtc",
                "-lwebrtc",
                "-L$(CORE_HOME)/../../third_party/openh264",
                "-lopenh264",
                "-L$(DEFAULT_DEPENDENCY_PATH)/lib",
                "<!@(pkg-config --libs libavutil)",
                "<!@(pkg-config --libs libavcodec)",
                "<!@(pkg-config --libs libavformat)",
                "<!@(pkg-config --libs libavfilter)",
                "-lSvtHevcEnc",
                "<!@(pkg-config --libs gstreamer-app-1.0 gstreamer-video-1.0)",
                "<!@(pkg-config --libs glib-2.0)",
                "<!@(pkg-config --libs fmt)",
            ],
        }
    ]
}
