{
    "targets": [
        {
            "target_name": "videoAnalyzer-sw",
            "sources": [
                "../addon.cc",
                "../VideoTranscoderWrapper.cc",
                "../VideoTranscoder.cpp",
                "../../../../core/common/JobTimer.cpp",
                "../../../../core/infraframe/MediaFramePipeline.cpp",
                "../../../../core/infraframe/FrameConverter.cpp",
                "../../../../core/infraframe/FrameAnalyzer.cpp",
                "../../../../core/infraframe/I420BufferManager.cpp",
                "../../../../core/infraframe/FrameProcessor.cpp",
                "../../../../core/infraframe/FFmpegDrawText.cpp",
                "../../../../core/infraframe/VCMFrameDecoder.cpp",
                "../../../../core/infraframe/VCMFrameEncoder.cpp",
                "../../../../core/infraframe/gst/BufferPool.cpp",
                "../../../../core/infraframe/gst/DecoderPipeline.cpp",
                "../../../../core/infraframe/gst/EncoderPipeline.cpp",
                "../../../../core/infraframe/gst/H264VideoDecoders.cpp",
                "../../../../core/infraframe/gst/H264VideoEncoders.cpp",
                "../../../../core/infraframe/gst/Helpers.cpp",
                "../../../../core/infraframe/gst/Support.cpp",
                "../../../../core/infraframe/gst/VideoDecoder.cpp",
                "../../../../core/infraframe/gst/VideoEncoder.cpp",
            ],
            "cflags_cc": [
                "-Wall",
                "-O$(OPTIMIZATION_LEVEL)",
                "-g",
                "-std=c++17",
                "-DWEBRTC_POSIX",
                "-DBUILD_FOR_ANALYTICS",
                "<!@(pkg-config --cflags-only-I gstreamer-1.0)",
                "<!@(pkg-config --cflags-only-I glib-2.0)",
            ],
            "cflags_cc!": [
                "-fno-exceptions",
            ],
            "include_dirs": [
                "<!(node -e \"require('nan')\")",
                "..",
                "$(CORE_HOME)/common",
                "$(CORE_HOME)/infraframe",
                "$(CORE_HOME)/../../third_party/webrtc/src",
                "$(CORE_HOME)/../../third_party/webrtc/src/third_party/libyuv/include",
                "$(DEFAULT_DEPENDENCY_PATH)/include",
                "$(CUSTOM_INCLUDE_PATH)",
            ],
            "libraries": [
                "-lboost_thread",
                "-llog4cxx",
                "-L$(CORE_HOME)/../../third_party/webrtc",
                "-lwebrtc",
                "-L$(DEFAULT_DEPENDENCY_PATH)/lib",
                "<!@(pkg-config --libs libavutil)",
                "<!@(pkg-config --libs libavcodec)",
                "<!@(pkg-config --libs libavformat)",
                "<!@(pkg-config --libs libavfilter)",
                "<!@(pkg-config --libs gstreamer-app-1.0)",
            ],
        },
    ]
}
